config/routes.rb
Adnet::Application.routes.draw do

  devise_for :users do 
    root :to => "devise/sessions#new"
  end
  
  scope "/dashboard" do
    resources :users
    resources :records
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :ecpm, :impressions, :revenue, :date, :user_id
  validates_presence_of :ecpm, :impressions, :revenue, :date, :user_id
  belongs_to :user

  def self.in_range( start_date, end_date)
    where( date: start_date..end_date ).order("date ASC")
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :name
  validates_uniqueness_of :email, case_sensiteve: false

  # Associations
  has_many :record

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
   records_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :only_allow_admin, only: [:new, :edit, :create, :update, :destroy]

  
  # GET /records
  # GET /records.json
  def index
    if params["/dashboard/records"].blank?
      @start_date = Date.today.beginning_of_month
      @end_date = Date.today
    else
      @start_date = Date.parse(params["/dashboard/records"][:start_date])
      @end_date = Date.parse(params["/dashboard/records"][:end_date])
      @user = User.find( params["/dashboard/records"][:user_id] ) unless params["/dashboard/records"][:user_id].blank?
    end
    
    if current_user.has_role? :admin
      if @user
        @records = @user.record.paginate( page: params[:page], per_page: 100).in_range( @start_date, @end_date )
      else
        @records = Record.paginate( page: params[:page], per_page: 100).in_range( @start_date, @end_date )
      end
    else
      @records = current_user.record.paginate( page: params[:page], per_page: 100).in_range( @start_date, @end_date )
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new
    @record.date = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to new_record_url, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  def only_allow_admin
    redirect_to root_url, alert: 'Not authorized' unless current_user.has_role? :admin
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :only_allow_admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    pass = Devise.friendly_token.first(8);
    params[:user][:password] = pass
    params[:user][:password_confirmation] = pass
    
    @user = User.new(params[:user])

    if @user.save
     redirect_to @user, notice: 'User was successfully created.'   
    else
      render action: "new" 
    end
    
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit" 
    end
    
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url 
    
  end

  def only_allow_admin
    redirect_to root_path, :alert => 'Not authorized as an administrator.' unless current_user.has_role? :admin
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper

	def is_admin?
		current_user.has_role? :admin
	end

	def get_all_users
		User.all
	end

	def get_total_impressions
		number_to_currency(@records.map {|x| x.impressions.to_i}.sum, unit: '', precision: 0)
	end

	def get_avg_ecpm
		number_to_currency(@records.map {|x| x.ecpm.to_f}.sum / @records.size)
	end

	def get_total_revenue
		number_to_currency(@records.map {|x| x.revenue.to_f}.sum)
	end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
	<header>
		<div class="navbar navbar-inverse">
		  <div class="navbar-inner">
		    <%= link_to root_path, class: 'brand' do %>
		    	Socialoholic <sub>Beta</sub>
		    <% end %>
		    <ul class="nav">
		    	<% if user_signed_in? %>
		    		<li><%= link_to 'Dashboard', records_path %></li>
		    		<% if is_admin? %>
		    			<li><%= link_to 'Users', users_path %></li>
	    			<% end %>
    			<% end %>
		    </ul>
		    <ul class="nav pull-right">
		    	<% if user_signed_in? %>
		    		
	    		  <li class="dropdown">
	    		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	    		      <%= current_user.name %>
	    		      <b class="caret"></b>
	    		    </a>
	    		    <ul class="dropdown-menu">
	    		    	<li><%= link_to 'Edit Details', edit_user_registration_path %></li>
	    		      <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
	    		    </ul>
	    		  </li>
	    		
		    		
	    		<% else %>
	    			<li><%= link_to 'Sign up', new_user_registration_path %></li>
	    			<li><%= link_to 'Sign in', new_user_session_path %></li>
    			<% end %>
		    </ul>
		  </div>
		</div>
	</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<title><%= content_for?(:title) ? yield(:title) + " - " : "" %> Socialoholic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:header) if content_for?(:header) %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/navigation' %>
		
		<div class="row">
			<%= render 'layouts/messages' %>
		</div>

		<div class="row">
			<%= yield %>
		</div>

	</div>

</body>
</html>

app/views/records/_form.html.erb
<%= simple_form_for(@record, html: { class: 'form-vertical' }) do |f| %>
  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <div class="form-inputs">

		<%= f.input :user_id, collection: get_all_users %>

    <%= f.input :date, as: :string, input_html: { class: 'date_picker', value: l(f.object.date)}  %>

  	<%= f.input :impressions, :wrapper => :prepend, :label => false do %>
  	  <%= content_tag :span, "Impressions", :class => "add-on" %>
  	  <%= f.input_field :impressions %>
  	<% end %>  
	
		<%= f.input :ecpm, :wrapper => :prepend, :label => false do %>
		  <%= content_tag :span, "eCPM", :class => "add-on" %>
		  <%= f.input_field :ecpm %>
		<% end %>  

		<%= f.input :revenue, :wrapper => :prepend, :label => false do %>
		  <%= content_tag :span, "Revenue", :class => "add-on" %>
		  <%= f.input_field :revenue %>
		<% end %>  

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/records/_table.html.erb
<table class="table table-striped">
  <tr>
    <th>Impressions</th>
    <th>eCPM</th>
    <th>Revenue</th>
    <th>Date</th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.impressions %></td>
    <td><%= record.ecpm %></td>
    <td>$<%= record.revenue %></td>
    <td><%= l record.date %></td>
    <% if is_admin? %>
      <td><%= record.user.name %></td>
      <td>
        <%= link_to 'Edit', edit_record_path(record) %>
        <%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<%= will_paginate @records %>

app/views/records/_tiles.html.erb
<ul class="thumbnails">
	<li id="impressions" class="span4 tile tile-purple">
		<h1></h1>
		<h3>Impressions</h3>
	</li>
	<li id="ecpm" class="span4 tile tile-green">
		<h1></h1>
		<h3>eCPM</h3>
	</li>
	<li id="revenue" class="span4 tile tile-teal">
		<h1></h1>
		<h3>Revenue</h3>
	</li>
</ul>

app/views/records/edit.html.erb
<% content_for(:title, 'Edit Record') %>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<% content_for(:title, 'Dashboard') %>

<% content_for( :header ) do %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js' %>
  <%= javascript_include_tag 'http://cdn.oesmith.co.uk/morris-0.4.1.min.js' %>
<% end %>


<% if is_admin? %>
  <div style="margin-bottom: 10px">
    <%= link_to 'New Record', new_record_path, class: 'btn btn-success' %>      
  </div>
<% else %>
  <div class="alert alert-info">
    All Numbers are subject to review and finalized numbers may differ slightly at the end of month.
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
<% end %>

<%= render 'tiles' %>

<div class="well">
  <%= simple_form_for( records_path, method: 'get', html: { class: 'form-vertical' }) do |f|%>

   <% if is_admin? %>
    <%= f.input :user_id, collection: get_all_users %>
   <% end %>

   <div class="input-prepend">
    <span class="add-on">From</span> 
    <%= f.input_field :start_date,
             as: :string, 
              class: 'date_picker', value: l(@start_date)
    %>
  </div>

  <div class="input-prepend">
   <span class="add-on">To</span> 
    <%= f.input_field :end_date,
             as: :string, 
             class: 'date_picker', value: l(@end_date)
    %>
  </div>

  <%= f.button :submit, 'Update' , class: 'btn btn-info' %>


  <% end %>
</div>

<%= javascript_tag do %>
  window.records = <%= raw @records.to_json %>
<% end %>  

<% if !is_admin? %>
  <div class="well">
    <div id="chart"></div>
  </div>
<% end %>

<%= render 'table' %>

app/views/records/new.html.erb
<% content_for(:title, 'New Record') %>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<% content_for(:title, 'Show Record') %>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>

<%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %>
  	<%= f.input :email %>
  	<% if action_name ==  'edit'%>
  		<%= f.input :password %>
  		<%= f.input :password_confirmation %>
  	<% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, 'Edit User') %>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% content_for(:title, 'Users List') %>

<div style="margin-bottom: 10px">
  <%= link_to 'Add New User', new_user_path, class: "btn btn-success" %>
</div>
  
<table class="table table-striped">
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<% content_for(:title, 'Add New User') %>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for(:title, 'Show User') %>
<p id="notice"><%= notice %></p>

<p><%= @user.name %></p>
<p><%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>